/*
Binance Public Spot API

OpenAPI Specifications for the Binance Public Spot API generated with [binance/binance-api-swagger/blob/master/spot_api.yaml](https://github.com/binance/binance-api-swagger/blob/master/spot_api.yaml) with commit [v1.2.0 release](https://github.com/binance/binance-api-swagger/commit/60d14be031c031600c853d5cdab86db5ab73603e)  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)

API version: 1.0
Contact: qishiwenjun@163.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package binanceapi

import (
	"encoding/json"
)

// IsolatedMarginAccountInfoBaseAsset struct for IsolatedMarginAccountInfoBaseAsset
type IsolatedMarginAccountInfoBaseAsset struct {
	Asset         string `json:"asset"`
	BorrowEnabled bool   `json:"borrowEnabled"`
	Borrowed      string `json:"borrowed"`
	Free          string `json:"free"`
	Interest      string `json:"interest"`
	Locked        string `json:"locked"`
	NetAsset      string `json:"netAsset"`
	NetAssetOfBtc string `json:"netAssetOfBtc"`
	RepayEnabled  bool   `json:"repayEnabled"`
	TotalAsset    string `json:"totalAsset"`
}

// NewIsolatedMarginAccountInfoBaseAsset instantiates a new IsolatedMarginAccountInfoBaseAsset object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIsolatedMarginAccountInfoBaseAsset(asset string, borrowEnabled bool, borrowed string, free string, interest string, locked string, netAsset string, netAssetOfBtc string, repayEnabled bool, totalAsset string) *IsolatedMarginAccountInfoBaseAsset {
	this := IsolatedMarginAccountInfoBaseAsset{}
	this.Asset = asset
	this.BorrowEnabled = borrowEnabled
	this.Borrowed = borrowed
	this.Free = free
	this.Interest = interest
	this.Locked = locked
	this.NetAsset = netAsset
	this.NetAssetOfBtc = netAssetOfBtc
	this.RepayEnabled = repayEnabled
	this.TotalAsset = totalAsset
	return &this
}

// NewIsolatedMarginAccountInfoBaseAssetWithDefaults instantiates a new IsolatedMarginAccountInfoBaseAsset object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIsolatedMarginAccountInfoBaseAssetWithDefaults() *IsolatedMarginAccountInfoBaseAsset {
	this := IsolatedMarginAccountInfoBaseAsset{}
	return &this
}

// GetAsset returns the Asset field value
func (o *IsolatedMarginAccountInfoBaseAsset) GetAsset() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Asset
}

// GetAssetOk returns a tuple with the Asset field value
// and a boolean to check if the value has been set.
func (o *IsolatedMarginAccountInfoBaseAsset) GetAssetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asset, true
}

// SetAsset sets field value
func (o *IsolatedMarginAccountInfoBaseAsset) SetAsset(v string) {
	o.Asset = v
}

// GetBorrowEnabled returns the BorrowEnabled field value
func (o *IsolatedMarginAccountInfoBaseAsset) GetBorrowEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.BorrowEnabled
}

// GetBorrowEnabledOk returns a tuple with the BorrowEnabled field value
// and a boolean to check if the value has been set.
func (o *IsolatedMarginAccountInfoBaseAsset) GetBorrowEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BorrowEnabled, true
}

// SetBorrowEnabled sets field value
func (o *IsolatedMarginAccountInfoBaseAsset) SetBorrowEnabled(v bool) {
	o.BorrowEnabled = v
}

// GetBorrowed returns the Borrowed field value
func (o *IsolatedMarginAccountInfoBaseAsset) GetBorrowed() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Borrowed
}

// GetBorrowedOk returns a tuple with the Borrowed field value
// and a boolean to check if the value has been set.
func (o *IsolatedMarginAccountInfoBaseAsset) GetBorrowedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Borrowed, true
}

// SetBorrowed sets field value
func (o *IsolatedMarginAccountInfoBaseAsset) SetBorrowed(v string) {
	o.Borrowed = v
}

// GetFree returns the Free field value
func (o *IsolatedMarginAccountInfoBaseAsset) GetFree() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Free
}

// GetFreeOk returns a tuple with the Free field value
// and a boolean to check if the value has been set.
func (o *IsolatedMarginAccountInfoBaseAsset) GetFreeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Free, true
}

// SetFree sets field value
func (o *IsolatedMarginAccountInfoBaseAsset) SetFree(v string) {
	o.Free = v
}

// GetInterest returns the Interest field value
func (o *IsolatedMarginAccountInfoBaseAsset) GetInterest() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Interest
}

// GetInterestOk returns a tuple with the Interest field value
// and a boolean to check if the value has been set.
func (o *IsolatedMarginAccountInfoBaseAsset) GetInterestOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Interest, true
}

// SetInterest sets field value
func (o *IsolatedMarginAccountInfoBaseAsset) SetInterest(v string) {
	o.Interest = v
}

// GetLocked returns the Locked field value
func (o *IsolatedMarginAccountInfoBaseAsset) GetLocked() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Locked
}

// GetLockedOk returns a tuple with the Locked field value
// and a boolean to check if the value has been set.
func (o *IsolatedMarginAccountInfoBaseAsset) GetLockedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Locked, true
}

// SetLocked sets field value
func (o *IsolatedMarginAccountInfoBaseAsset) SetLocked(v string) {
	o.Locked = v
}

// GetNetAsset returns the NetAsset field value
func (o *IsolatedMarginAccountInfoBaseAsset) GetNetAsset() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NetAsset
}

// GetNetAssetOk returns a tuple with the NetAsset field value
// and a boolean to check if the value has been set.
func (o *IsolatedMarginAccountInfoBaseAsset) GetNetAssetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetAsset, true
}

// SetNetAsset sets field value
func (o *IsolatedMarginAccountInfoBaseAsset) SetNetAsset(v string) {
	o.NetAsset = v
}

// GetNetAssetOfBtc returns the NetAssetOfBtc field value
func (o *IsolatedMarginAccountInfoBaseAsset) GetNetAssetOfBtc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NetAssetOfBtc
}

// GetNetAssetOfBtcOk returns a tuple with the NetAssetOfBtc field value
// and a boolean to check if the value has been set.
func (o *IsolatedMarginAccountInfoBaseAsset) GetNetAssetOfBtcOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetAssetOfBtc, true
}

// SetNetAssetOfBtc sets field value
func (o *IsolatedMarginAccountInfoBaseAsset) SetNetAssetOfBtc(v string) {
	o.NetAssetOfBtc = v
}

// GetRepayEnabled returns the RepayEnabled field value
func (o *IsolatedMarginAccountInfoBaseAsset) GetRepayEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RepayEnabled
}

// GetRepayEnabledOk returns a tuple with the RepayEnabled field value
// and a boolean to check if the value has been set.
func (o *IsolatedMarginAccountInfoBaseAsset) GetRepayEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RepayEnabled, true
}

// SetRepayEnabled sets field value
func (o *IsolatedMarginAccountInfoBaseAsset) SetRepayEnabled(v bool) {
	o.RepayEnabled = v
}

// GetTotalAsset returns the TotalAsset field value
func (o *IsolatedMarginAccountInfoBaseAsset) GetTotalAsset() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TotalAsset
}

// GetTotalAssetOk returns a tuple with the TotalAsset field value
// and a boolean to check if the value has been set.
func (o *IsolatedMarginAccountInfoBaseAsset) GetTotalAssetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalAsset, true
}

// SetTotalAsset sets field value
func (o *IsolatedMarginAccountInfoBaseAsset) SetTotalAsset(v string) {
	o.TotalAsset = v
}

func (o IsolatedMarginAccountInfoBaseAsset) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["asset"] = o.Asset
	}
	if true {
		toSerialize["borrowEnabled"] = o.BorrowEnabled
	}
	if true {
		toSerialize["borrowed"] = o.Borrowed
	}
	if true {
		toSerialize["free"] = o.Free
	}
	if true {
		toSerialize["interest"] = o.Interest
	}
	if true {
		toSerialize["locked"] = o.Locked
	}
	if true {
		toSerialize["netAsset"] = o.NetAsset
	}
	if true {
		toSerialize["netAssetOfBtc"] = o.NetAssetOfBtc
	}
	if true {
		toSerialize["repayEnabled"] = o.RepayEnabled
	}
	if true {
		toSerialize["totalAsset"] = o.TotalAsset
	}
	return json.Marshal(toSerialize)
}

type NullableIsolatedMarginAccountInfoBaseAsset struct {
	value *IsolatedMarginAccountInfoBaseAsset
	isSet bool
}

func (v NullableIsolatedMarginAccountInfoBaseAsset) Get() *IsolatedMarginAccountInfoBaseAsset {
	return v.value
}

func (v *NullableIsolatedMarginAccountInfoBaseAsset) Set(val *IsolatedMarginAccountInfoBaseAsset) {
	v.value = val
	v.isSet = true
}

func (v NullableIsolatedMarginAccountInfoBaseAsset) IsSet() bool {
	return v.isSet
}

func (v *NullableIsolatedMarginAccountInfoBaseAsset) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIsolatedMarginAccountInfoBaseAsset(val *IsolatedMarginAccountInfoBaseAsset) *NullableIsolatedMarginAccountInfoBaseAsset {
	return &NullableIsolatedMarginAccountInfoBaseAsset{value: val, isSet: true}
}

func (v NullableIsolatedMarginAccountInfoBaseAsset) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIsolatedMarginAccountInfoBaseAsset) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
