/*
Binance Public Spot API

OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineResponse20088Data struct for InlineResponse20088Data
type InlineResponse20088Data struct {
	WorkerDatas []InlineResponse20088DataWorkerDatas `json:"workerDatas"`
	TotalNum int64 `json:"totalNum"`
	PageSize int64 `json:"pageSize"`
}

// NewInlineResponse20088Data instantiates a new InlineResponse20088Data object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20088Data(workerDatas []InlineResponse20088DataWorkerDatas, totalNum int64, pageSize int64) *InlineResponse20088Data {
	this := InlineResponse20088Data{}
	this.WorkerDatas = workerDatas
	this.TotalNum = totalNum
	this.PageSize = pageSize
	return &this
}

// NewInlineResponse20088DataWithDefaults instantiates a new InlineResponse20088Data object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20088DataWithDefaults() *InlineResponse20088Data {
	this := InlineResponse20088Data{}
	return &this
}

// GetWorkerDatas returns the WorkerDatas field value
func (o *InlineResponse20088Data) GetWorkerDatas() []InlineResponse20088DataWorkerDatas {
	if o == nil {
		var ret []InlineResponse20088DataWorkerDatas
		return ret
	}

	return o.WorkerDatas
}

// GetWorkerDatasOk returns a tuple with the WorkerDatas field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20088Data) GetWorkerDatasOk() (*[]InlineResponse20088DataWorkerDatas, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.WorkerDatas, true
}

// SetWorkerDatas sets field value
func (o *InlineResponse20088Data) SetWorkerDatas(v []InlineResponse20088DataWorkerDatas) {
	o.WorkerDatas = v
}

// GetTotalNum returns the TotalNum field value
func (o *InlineResponse20088Data) GetTotalNum() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalNum
}

// GetTotalNumOk returns a tuple with the TotalNum field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20088Data) GetTotalNumOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TotalNum, true
}

// SetTotalNum sets field value
func (o *InlineResponse20088Data) SetTotalNum(v int64) {
	o.TotalNum = v
}

// GetPageSize returns the PageSize field value
func (o *InlineResponse20088Data) GetPageSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20088Data) GetPageSizeOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PageSize, true
}

// SetPageSize sets field value
func (o *InlineResponse20088Data) SetPageSize(v int64) {
	o.PageSize = v
}

func (o InlineResponse20088Data) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["workerDatas"] = o.WorkerDatas
	}
	if true {
		toSerialize["totalNum"] = o.TotalNum
	}
	if true {
		toSerialize["pageSize"] = o.PageSize
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20088Data struct {
	value *InlineResponse20088Data
	isSet bool
}

func (v NullableInlineResponse20088Data) Get() *InlineResponse20088Data {
	return v.value
}

func (v *NullableInlineResponse20088Data) Set(val *InlineResponse20088Data) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20088Data) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20088Data) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20088Data(val *InlineResponse20088Data) *NullableInlineResponse20088Data {
	return &NullableInlineResponse20088Data{value: val, isSet: true}
}

func (v NullableInlineResponse20088Data) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20088Data) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


