/*
Binance Public Spot API

OpenAPI Specifications for the Binance Public Spot API generated with [binance/binance-api-swagger/blob/master/spot_api.yaml](https://github.com/binance/binance-api-swagger/blob/master/spot_api.yaml) with commit [v1.2.0 release](https://github.com/binance/binance-api-swagger/commit/60d14be031c031600c853d5cdab86db5ab73603e)  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)

API version: 1.0
Contact: qishiwenjun@163.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package binanceapi

import (
	"encoding/json"
)

// InlineResponse20028 struct for InlineResponse20028
type InlineResponse20028 struct {
	Asset             string `json:"asset"`
	DailyInterestRate string `json:"dailyInterestRate"`
	Timestamp         int64  `json:"timestamp"`
	VipLevel          int32  `json:"vipLevel"`
}

// NewInlineResponse20028 instantiates a new InlineResponse20028 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20028(asset string, dailyInterestRate string, timestamp int64, vipLevel int32) *InlineResponse20028 {
	this := InlineResponse20028{}
	this.Asset = asset
	this.DailyInterestRate = dailyInterestRate
	this.Timestamp = timestamp
	this.VipLevel = vipLevel
	return &this
}

// NewInlineResponse20028WithDefaults instantiates a new InlineResponse20028 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20028WithDefaults() *InlineResponse20028 {
	this := InlineResponse20028{}
	return &this
}

// GetAsset returns the Asset field value
func (o *InlineResponse20028) GetAsset() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Asset
}

// GetAssetOk returns a tuple with the Asset field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20028) GetAssetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asset, true
}

// SetAsset sets field value
func (o *InlineResponse20028) SetAsset(v string) {
	o.Asset = v
}

// GetDailyInterestRate returns the DailyInterestRate field value
func (o *InlineResponse20028) GetDailyInterestRate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DailyInterestRate
}

// GetDailyInterestRateOk returns a tuple with the DailyInterestRate field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20028) GetDailyInterestRateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DailyInterestRate, true
}

// SetDailyInterestRate sets field value
func (o *InlineResponse20028) SetDailyInterestRate(v string) {
	o.DailyInterestRate = v
}

// GetTimestamp returns the Timestamp field value
func (o *InlineResponse20028) GetTimestamp() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20028) GetTimestampOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *InlineResponse20028) SetTimestamp(v int64) {
	o.Timestamp = v
}

// GetVipLevel returns the VipLevel field value
func (o *InlineResponse20028) GetVipLevel() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.VipLevel
}

// GetVipLevelOk returns a tuple with the VipLevel field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20028) GetVipLevelOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VipLevel, true
}

// SetVipLevel sets field value
func (o *InlineResponse20028) SetVipLevel(v int32) {
	o.VipLevel = v
}

func (o InlineResponse20028) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["asset"] = o.Asset
	}
	if true {
		toSerialize["dailyInterestRate"] = o.DailyInterestRate
	}
	if true {
		toSerialize["timestamp"] = o.Timestamp
	}
	if true {
		toSerialize["vipLevel"] = o.VipLevel
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20028 struct {
	value *InlineResponse20028
	isSet bool
}

func (v NullableInlineResponse20028) Get() *InlineResponse20028 {
	return v.value
}

func (v *NullableInlineResponse20028) Set(val *InlineResponse20028) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20028) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20028) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20028(val *InlineResponse20028) *NullableInlineResponse20028 {
	return &NullableInlineResponse20028{value: val, isSet: true}
}

func (v NullableInlineResponse20028) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20028) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
