/*
Binance Public Spot API

OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineResponse20027 struct for InlineResponse20027
type InlineResponse20027 struct {
	Symbol string `json:"symbol"`
	Base string `json:"base"`
	Quote string `json:"quote"`
	IsMarginTrade bool `json:"isMarginTrade"`
	IsBuyAllowed bool `json:"isBuyAllowed"`
	IsSellAllowed bool `json:"isSellAllowed"`
}

// NewInlineResponse20027 instantiates a new InlineResponse20027 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20027(symbol string, base string, quote string, isMarginTrade bool, isBuyAllowed bool, isSellAllowed bool) *InlineResponse20027 {
	this := InlineResponse20027{}
	this.Symbol = symbol
	this.Base = base
	this.Quote = quote
	this.IsMarginTrade = isMarginTrade
	this.IsBuyAllowed = isBuyAllowed
	this.IsSellAllowed = isSellAllowed
	return &this
}

// NewInlineResponse20027WithDefaults instantiates a new InlineResponse20027 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20027WithDefaults() *InlineResponse20027 {
	this := InlineResponse20027{}
	return &this
}

// GetSymbol returns the Symbol field value
func (o *InlineResponse20027) GetSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20027) GetSymbolOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Symbol, true
}

// SetSymbol sets field value
func (o *InlineResponse20027) SetSymbol(v string) {
	o.Symbol = v
}

// GetBase returns the Base field value
func (o *InlineResponse20027) GetBase() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Base
}

// GetBaseOk returns a tuple with the Base field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20027) GetBaseOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Base, true
}

// SetBase sets field value
func (o *InlineResponse20027) SetBase(v string) {
	o.Base = v
}

// GetQuote returns the Quote field value
func (o *InlineResponse20027) GetQuote() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Quote
}

// GetQuoteOk returns a tuple with the Quote field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20027) GetQuoteOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Quote, true
}

// SetQuote sets field value
func (o *InlineResponse20027) SetQuote(v string) {
	o.Quote = v
}

// GetIsMarginTrade returns the IsMarginTrade field value
func (o *InlineResponse20027) GetIsMarginTrade() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsMarginTrade
}

// GetIsMarginTradeOk returns a tuple with the IsMarginTrade field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20027) GetIsMarginTradeOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.IsMarginTrade, true
}

// SetIsMarginTrade sets field value
func (o *InlineResponse20027) SetIsMarginTrade(v bool) {
	o.IsMarginTrade = v
}

// GetIsBuyAllowed returns the IsBuyAllowed field value
func (o *InlineResponse20027) GetIsBuyAllowed() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsBuyAllowed
}

// GetIsBuyAllowedOk returns a tuple with the IsBuyAllowed field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20027) GetIsBuyAllowedOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.IsBuyAllowed, true
}

// SetIsBuyAllowed sets field value
func (o *InlineResponse20027) SetIsBuyAllowed(v bool) {
	o.IsBuyAllowed = v
}

// GetIsSellAllowed returns the IsSellAllowed field value
func (o *InlineResponse20027) GetIsSellAllowed() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsSellAllowed
}

// GetIsSellAllowedOk returns a tuple with the IsSellAllowed field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20027) GetIsSellAllowedOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.IsSellAllowed, true
}

// SetIsSellAllowed sets field value
func (o *InlineResponse20027) SetIsSellAllowed(v bool) {
	o.IsSellAllowed = v
}

func (o InlineResponse20027) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["symbol"] = o.Symbol
	}
	if true {
		toSerialize["base"] = o.Base
	}
	if true {
		toSerialize["quote"] = o.Quote
	}
	if true {
		toSerialize["isMarginTrade"] = o.IsMarginTrade
	}
	if true {
		toSerialize["isBuyAllowed"] = o.IsBuyAllowed
	}
	if true {
		toSerialize["isSellAllowed"] = o.IsSellAllowed
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20027 struct {
	value *InlineResponse20027
	isSet bool
}

func (v NullableInlineResponse20027) Get() *InlineResponse20027 {
	return v.value
}

func (v *NullableInlineResponse20027) Set(val *InlineResponse20027) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20027) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20027) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20027(val *InlineResponse20027) *NullableInlineResponse20027 {
	return &NullableInlineResponse20027{value: val, isSet: true}
}

func (v NullableInlineResponse20027) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20027) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


