/*
Binance Public Spot API

OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package binanceapi

import (
	"encoding/json"
)

// InlineResponse20052 struct for InlineResponse20052
type InlineResponse20052 struct {
	TotalCount int64 `json:"totalCount"`
	MasterAccountTotalAsset string `json:"masterAccountTotalAsset"`
	SpotSubUserAssetBtcVoList []InlineResponse20052SpotSubUserAssetBtcVoList `json:"spotSubUserAssetBtcVoList"`
}

// NewInlineResponse20052 instantiates a new InlineResponse20052 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20052(totalCount int64, masterAccountTotalAsset string, spotSubUserAssetBtcVoList []InlineResponse20052SpotSubUserAssetBtcVoList) *InlineResponse20052 {
	this := InlineResponse20052{}
	this.TotalCount = totalCount
	this.MasterAccountTotalAsset = masterAccountTotalAsset
	this.SpotSubUserAssetBtcVoList = spotSubUserAssetBtcVoList
	return &this
}

// NewInlineResponse20052WithDefaults instantiates a new InlineResponse20052 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20052WithDefaults() *InlineResponse20052 {
	this := InlineResponse20052{}
	return &this
}

// GetTotalCount returns the TotalCount field value
func (o *InlineResponse20052) GetTotalCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20052) GetTotalCountOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *InlineResponse20052) SetTotalCount(v int64) {
	o.TotalCount = v
}

// GetMasterAccountTotalAsset returns the MasterAccountTotalAsset field value
func (o *InlineResponse20052) GetMasterAccountTotalAsset() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MasterAccountTotalAsset
}

// GetMasterAccountTotalAssetOk returns a tuple with the MasterAccountTotalAsset field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20052) GetMasterAccountTotalAssetOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.MasterAccountTotalAsset, true
}

// SetMasterAccountTotalAsset sets field value
func (o *InlineResponse20052) SetMasterAccountTotalAsset(v string) {
	o.MasterAccountTotalAsset = v
}

// GetSpotSubUserAssetBtcVoList returns the SpotSubUserAssetBtcVoList field value
func (o *InlineResponse20052) GetSpotSubUserAssetBtcVoList() []InlineResponse20052SpotSubUserAssetBtcVoList {
	if o == nil {
		var ret []InlineResponse20052SpotSubUserAssetBtcVoList
		return ret
	}

	return o.SpotSubUserAssetBtcVoList
}

// GetSpotSubUserAssetBtcVoListOk returns a tuple with the SpotSubUserAssetBtcVoList field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20052) GetSpotSubUserAssetBtcVoListOk() (*[]InlineResponse20052SpotSubUserAssetBtcVoList, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SpotSubUserAssetBtcVoList, true
}

// SetSpotSubUserAssetBtcVoList sets field value
func (o *InlineResponse20052) SetSpotSubUserAssetBtcVoList(v []InlineResponse20052SpotSubUserAssetBtcVoList) {
	o.SpotSubUserAssetBtcVoList = v
}

func (o InlineResponse20052) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["totalCount"] = o.TotalCount
	}
	if true {
		toSerialize["masterAccountTotalAsset"] = o.MasterAccountTotalAsset
	}
	if true {
		toSerialize["spotSubUserAssetBtcVoList"] = o.SpotSubUserAssetBtcVoList
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20052 struct {
	value *InlineResponse20052
	isSet bool
}

func (v NullableInlineResponse20052) Get() *InlineResponse20052 {
	return v.value
}

func (v *NullableInlineResponse20052) Set(val *InlineResponse20052) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20052) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20052) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20052(val *InlineResponse20052) *NullableInlineResponse20052 {
	return &NullableInlineResponse20052{value: val, isSet: true}
}

func (v NullableInlineResponse20052) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20052) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


