/*
Binance Public Spot API

OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// IsolatedMarginAccountInfoAssets struct for IsolatedMarginAccountInfoAssets
type IsolatedMarginAccountInfoAssets struct {
	BaseAsset IsolatedMarginAccountInfoBaseAsset `json:"baseAsset"`
	QuoteAsset IsolatedMarginAccountInfoQuoteAsset `json:"quoteAsset"`
	Symbol string `json:"symbol"`
	IsolatedCreated bool `json:"isolatedCreated"`
	// true-enabled, false-disabled
	Enabled bool `json:"enabled"`
	MarginLevel string `json:"marginLevel"`
	// \"EXCESSIVE\", \"NORMAL\", \"MARGIN_CALL\", \"PRE_LIQUIDATION\", \"FORCE_LIQUIDATION\"
	MarginLevelStatus string `json:"marginLevelStatus"`
	MarginRatio string `json:"marginRatio"`
	IndexPrice string `json:"indexPrice"`
	LiquidatePrice string `json:"liquidatePrice"`
	LiquidateRate string `json:"liquidateRate"`
	TradeEnabled bool `json:"tradeEnabled"`
}

// NewIsolatedMarginAccountInfoAssets instantiates a new IsolatedMarginAccountInfoAssets object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIsolatedMarginAccountInfoAssets(baseAsset IsolatedMarginAccountInfoBaseAsset, quoteAsset IsolatedMarginAccountInfoQuoteAsset, symbol string, isolatedCreated bool, enabled bool, marginLevel string, marginLevelStatus string, marginRatio string, indexPrice string, liquidatePrice string, liquidateRate string, tradeEnabled bool) *IsolatedMarginAccountInfoAssets {
	this := IsolatedMarginAccountInfoAssets{}
	this.BaseAsset = baseAsset
	this.QuoteAsset = quoteAsset
	this.Symbol = symbol
	this.IsolatedCreated = isolatedCreated
	this.Enabled = enabled
	this.MarginLevel = marginLevel
	this.MarginLevelStatus = marginLevelStatus
	this.MarginRatio = marginRatio
	this.IndexPrice = indexPrice
	this.LiquidatePrice = liquidatePrice
	this.LiquidateRate = liquidateRate
	this.TradeEnabled = tradeEnabled
	return &this
}

// NewIsolatedMarginAccountInfoAssetsWithDefaults instantiates a new IsolatedMarginAccountInfoAssets object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIsolatedMarginAccountInfoAssetsWithDefaults() *IsolatedMarginAccountInfoAssets {
	this := IsolatedMarginAccountInfoAssets{}
	return &this
}

// GetBaseAsset returns the BaseAsset field value
func (o *IsolatedMarginAccountInfoAssets) GetBaseAsset() IsolatedMarginAccountInfoBaseAsset {
	if o == nil {
		var ret IsolatedMarginAccountInfoBaseAsset
		return ret
	}

	return o.BaseAsset
}

// GetBaseAssetOk returns a tuple with the BaseAsset field value
// and a boolean to check if the value has been set.
func (o *IsolatedMarginAccountInfoAssets) GetBaseAssetOk() (*IsolatedMarginAccountInfoBaseAsset, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.BaseAsset, true
}

// SetBaseAsset sets field value
func (o *IsolatedMarginAccountInfoAssets) SetBaseAsset(v IsolatedMarginAccountInfoBaseAsset) {
	o.BaseAsset = v
}

// GetQuoteAsset returns the QuoteAsset field value
func (o *IsolatedMarginAccountInfoAssets) GetQuoteAsset() IsolatedMarginAccountInfoQuoteAsset {
	if o == nil {
		var ret IsolatedMarginAccountInfoQuoteAsset
		return ret
	}

	return o.QuoteAsset
}

// GetQuoteAssetOk returns a tuple with the QuoteAsset field value
// and a boolean to check if the value has been set.
func (o *IsolatedMarginAccountInfoAssets) GetQuoteAssetOk() (*IsolatedMarginAccountInfoQuoteAsset, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.QuoteAsset, true
}

// SetQuoteAsset sets field value
func (o *IsolatedMarginAccountInfoAssets) SetQuoteAsset(v IsolatedMarginAccountInfoQuoteAsset) {
	o.QuoteAsset = v
}

// GetSymbol returns the Symbol field value
func (o *IsolatedMarginAccountInfoAssets) GetSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value
// and a boolean to check if the value has been set.
func (o *IsolatedMarginAccountInfoAssets) GetSymbolOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Symbol, true
}

// SetSymbol sets field value
func (o *IsolatedMarginAccountInfoAssets) SetSymbol(v string) {
	o.Symbol = v
}

// GetIsolatedCreated returns the IsolatedCreated field value
func (o *IsolatedMarginAccountInfoAssets) GetIsolatedCreated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsolatedCreated
}

// GetIsolatedCreatedOk returns a tuple with the IsolatedCreated field value
// and a boolean to check if the value has been set.
func (o *IsolatedMarginAccountInfoAssets) GetIsolatedCreatedOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.IsolatedCreated, true
}

// SetIsolatedCreated sets field value
func (o *IsolatedMarginAccountInfoAssets) SetIsolatedCreated(v bool) {
	o.IsolatedCreated = v
}

// GetEnabled returns the Enabled field value
func (o *IsolatedMarginAccountInfoAssets) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *IsolatedMarginAccountInfoAssets) GetEnabledOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *IsolatedMarginAccountInfoAssets) SetEnabled(v bool) {
	o.Enabled = v
}

// GetMarginLevel returns the MarginLevel field value
func (o *IsolatedMarginAccountInfoAssets) GetMarginLevel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MarginLevel
}

// GetMarginLevelOk returns a tuple with the MarginLevel field value
// and a boolean to check if the value has been set.
func (o *IsolatedMarginAccountInfoAssets) GetMarginLevelOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.MarginLevel, true
}

// SetMarginLevel sets field value
func (o *IsolatedMarginAccountInfoAssets) SetMarginLevel(v string) {
	o.MarginLevel = v
}

// GetMarginLevelStatus returns the MarginLevelStatus field value
func (o *IsolatedMarginAccountInfoAssets) GetMarginLevelStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MarginLevelStatus
}

// GetMarginLevelStatusOk returns a tuple with the MarginLevelStatus field value
// and a boolean to check if the value has been set.
func (o *IsolatedMarginAccountInfoAssets) GetMarginLevelStatusOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.MarginLevelStatus, true
}

// SetMarginLevelStatus sets field value
func (o *IsolatedMarginAccountInfoAssets) SetMarginLevelStatus(v string) {
	o.MarginLevelStatus = v
}

// GetMarginRatio returns the MarginRatio field value
func (o *IsolatedMarginAccountInfoAssets) GetMarginRatio() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MarginRatio
}

// GetMarginRatioOk returns a tuple with the MarginRatio field value
// and a boolean to check if the value has been set.
func (o *IsolatedMarginAccountInfoAssets) GetMarginRatioOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.MarginRatio, true
}

// SetMarginRatio sets field value
func (o *IsolatedMarginAccountInfoAssets) SetMarginRatio(v string) {
	o.MarginRatio = v
}

// GetIndexPrice returns the IndexPrice field value
func (o *IsolatedMarginAccountInfoAssets) GetIndexPrice() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndexPrice
}

// GetIndexPriceOk returns a tuple with the IndexPrice field value
// and a boolean to check if the value has been set.
func (o *IsolatedMarginAccountInfoAssets) GetIndexPriceOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.IndexPrice, true
}

// SetIndexPrice sets field value
func (o *IsolatedMarginAccountInfoAssets) SetIndexPrice(v string) {
	o.IndexPrice = v
}

// GetLiquidatePrice returns the LiquidatePrice field value
func (o *IsolatedMarginAccountInfoAssets) GetLiquidatePrice() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LiquidatePrice
}

// GetLiquidatePriceOk returns a tuple with the LiquidatePrice field value
// and a boolean to check if the value has been set.
func (o *IsolatedMarginAccountInfoAssets) GetLiquidatePriceOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.LiquidatePrice, true
}

// SetLiquidatePrice sets field value
func (o *IsolatedMarginAccountInfoAssets) SetLiquidatePrice(v string) {
	o.LiquidatePrice = v
}

// GetLiquidateRate returns the LiquidateRate field value
func (o *IsolatedMarginAccountInfoAssets) GetLiquidateRate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LiquidateRate
}

// GetLiquidateRateOk returns a tuple with the LiquidateRate field value
// and a boolean to check if the value has been set.
func (o *IsolatedMarginAccountInfoAssets) GetLiquidateRateOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.LiquidateRate, true
}

// SetLiquidateRate sets field value
func (o *IsolatedMarginAccountInfoAssets) SetLiquidateRate(v string) {
	o.LiquidateRate = v
}

// GetTradeEnabled returns the TradeEnabled field value
func (o *IsolatedMarginAccountInfoAssets) GetTradeEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.TradeEnabled
}

// GetTradeEnabledOk returns a tuple with the TradeEnabled field value
// and a boolean to check if the value has been set.
func (o *IsolatedMarginAccountInfoAssets) GetTradeEnabledOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TradeEnabled, true
}

// SetTradeEnabled sets field value
func (o *IsolatedMarginAccountInfoAssets) SetTradeEnabled(v bool) {
	o.TradeEnabled = v
}

func (o IsolatedMarginAccountInfoAssets) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["baseAsset"] = o.BaseAsset
	}
	if true {
		toSerialize["quoteAsset"] = o.QuoteAsset
	}
	if true {
		toSerialize["symbol"] = o.Symbol
	}
	if true {
		toSerialize["isolatedCreated"] = o.IsolatedCreated
	}
	if true {
		toSerialize["enabled"] = o.Enabled
	}
	if true {
		toSerialize["marginLevel"] = o.MarginLevel
	}
	if true {
		toSerialize["marginLevelStatus"] = o.MarginLevelStatus
	}
	if true {
		toSerialize["marginRatio"] = o.MarginRatio
	}
	if true {
		toSerialize["indexPrice"] = o.IndexPrice
	}
	if true {
		toSerialize["liquidatePrice"] = o.LiquidatePrice
	}
	if true {
		toSerialize["liquidateRate"] = o.LiquidateRate
	}
	if true {
		toSerialize["tradeEnabled"] = o.TradeEnabled
	}
	return json.Marshal(toSerialize)
}

type NullableIsolatedMarginAccountInfoAssets struct {
	value *IsolatedMarginAccountInfoAssets
	isSet bool
}

func (v NullableIsolatedMarginAccountInfoAssets) Get() *IsolatedMarginAccountInfoAssets {
	return v.value
}

func (v *NullableIsolatedMarginAccountInfoAssets) Set(val *IsolatedMarginAccountInfoAssets) {
	v.value = val
	v.isSet = true
}

func (v NullableIsolatedMarginAccountInfoAssets) IsSet() bool {
	return v.isSet
}

func (v *NullableIsolatedMarginAccountInfoAssets) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIsolatedMarginAccountInfoAssets(val *IsolatedMarginAccountInfoAssets) *NullableIsolatedMarginAccountInfoAssets {
	return &NullableIsolatedMarginAccountInfoAssets{value: val, isSet: true}
}

func (v NullableIsolatedMarginAccountInfoAssets) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIsolatedMarginAccountInfoAssets) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


