/*
Binance Public Spot API

OpenAPI Specifications for the Binance Public Spot API generated with [binance/binance-api-swagger/blob/master/spot_api.yaml](https://github.com/binance/binance-api-swagger/blob/master/spot_api.yaml) with commit [v1.2.0 release](https://github.com/binance/binance-api-swagger/commit/60d14be031c031600c853d5cdab86db5ab73603e)  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)

API version: 1.0
Contact: qishiwenjun@163.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package binanceapi

import (
	"encoding/json"
)

// InlineResponse20020Orders struct for InlineResponse20020Orders
type InlineResponse20020Orders struct {
	Symbol        string `json:"symbol"`
	OrderId       int64  `json:"orderId"`
	ClientOrderId string `json:"clientOrderId"`
}

// NewInlineResponse20020Orders instantiates a new InlineResponse20020Orders object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20020Orders(symbol string, orderId int64, clientOrderId string) *InlineResponse20020Orders {
	this := InlineResponse20020Orders{}
	this.Symbol = symbol
	this.OrderId = orderId
	this.ClientOrderId = clientOrderId
	return &this
}

// NewInlineResponse20020OrdersWithDefaults instantiates a new InlineResponse20020Orders object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20020OrdersWithDefaults() *InlineResponse20020Orders {
	this := InlineResponse20020Orders{}
	return &this
}

// GetSymbol returns the Symbol field value
func (o *InlineResponse20020Orders) GetSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20020Orders) GetSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Symbol, true
}

// SetSymbol sets field value
func (o *InlineResponse20020Orders) SetSymbol(v string) {
	o.Symbol = v
}

// GetOrderId returns the OrderId field value
func (o *InlineResponse20020Orders) GetOrderId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20020Orders) GetOrderIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderId, true
}

// SetOrderId sets field value
func (o *InlineResponse20020Orders) SetOrderId(v int64) {
	o.OrderId = v
}

// GetClientOrderId returns the ClientOrderId field value
func (o *InlineResponse20020Orders) GetClientOrderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientOrderId
}

// GetClientOrderIdOk returns a tuple with the ClientOrderId field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20020Orders) GetClientOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientOrderId, true
}

// SetClientOrderId sets field value
func (o *InlineResponse20020Orders) SetClientOrderId(v string) {
	o.ClientOrderId = v
}

func (o InlineResponse20020Orders) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["symbol"] = o.Symbol
	}
	if true {
		toSerialize["orderId"] = o.OrderId
	}
	if true {
		toSerialize["clientOrderId"] = o.ClientOrderId
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20020Orders struct {
	value *InlineResponse20020Orders
	isSet bool
}

func (v NullableInlineResponse20020Orders) Get() *InlineResponse20020Orders {
	return v.value
}

func (v *NullableInlineResponse20020Orders) Set(val *InlineResponse20020Orders) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20020Orders) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20020Orders) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20020Orders(val *InlineResponse20020Orders) *NullableInlineResponse20020Orders {
	return &NullableInlineResponse20020Orders{value: val, isSet: true}
}

func (v NullableInlineResponse20020Orders) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20020Orders) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
