/*
Binance Public Spot API

OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package binanceapi

import (
	"encoding/json"
)

// MarginTransferDetailsRows struct for MarginTransferDetailsRows
type MarginTransferDetailsRows struct {
	Amount string `json:"amount"`
	Asset string `json:"asset"`
	Status string `json:"status"`
	Timestamp int64 `json:"timestamp"`
	TxId int64 `json:"txId"`
	TransFrom string `json:"transFrom"`
	TransTo string `json:"transTo"`
}

// NewMarginTransferDetailsRows instantiates a new MarginTransferDetailsRows object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMarginTransferDetailsRows(amount string, asset string, status string, timestamp int64, txId int64, transFrom string, transTo string) *MarginTransferDetailsRows {
	this := MarginTransferDetailsRows{}
	this.Amount = amount
	this.Asset = asset
	this.Status = status
	this.Timestamp = timestamp
	this.TxId = txId
	this.TransFrom = transFrom
	this.TransTo = transTo
	return &this
}

// NewMarginTransferDetailsRowsWithDefaults instantiates a new MarginTransferDetailsRows object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMarginTransferDetailsRowsWithDefaults() *MarginTransferDetailsRows {
	this := MarginTransferDetailsRows{}
	return &this
}

// GetAmount returns the Amount field value
func (o *MarginTransferDetailsRows) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *MarginTransferDetailsRows) GetAmountOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *MarginTransferDetailsRows) SetAmount(v string) {
	o.Amount = v
}

// GetAsset returns the Asset field value
func (o *MarginTransferDetailsRows) GetAsset() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Asset
}

// GetAssetOk returns a tuple with the Asset field value
// and a boolean to check if the value has been set.
func (o *MarginTransferDetailsRows) GetAssetOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Asset, true
}

// SetAsset sets field value
func (o *MarginTransferDetailsRows) SetAsset(v string) {
	o.Asset = v
}

// GetStatus returns the Status field value
func (o *MarginTransferDetailsRows) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *MarginTransferDetailsRows) GetStatusOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *MarginTransferDetailsRows) SetStatus(v string) {
	o.Status = v
}

// GetTimestamp returns the Timestamp field value
func (o *MarginTransferDetailsRows) GetTimestamp() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *MarginTransferDetailsRows) GetTimestampOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *MarginTransferDetailsRows) SetTimestamp(v int64) {
	o.Timestamp = v
}

// GetTxId returns the TxId field value
func (o *MarginTransferDetailsRows) GetTxId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TxId
}

// GetTxIdOk returns a tuple with the TxId field value
// and a boolean to check if the value has been set.
func (o *MarginTransferDetailsRows) GetTxIdOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TxId, true
}

// SetTxId sets field value
func (o *MarginTransferDetailsRows) SetTxId(v int64) {
	o.TxId = v
}

// GetTransFrom returns the TransFrom field value
func (o *MarginTransferDetailsRows) GetTransFrom() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransFrom
}

// GetTransFromOk returns a tuple with the TransFrom field value
// and a boolean to check if the value has been set.
func (o *MarginTransferDetailsRows) GetTransFromOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TransFrom, true
}

// SetTransFrom sets field value
func (o *MarginTransferDetailsRows) SetTransFrom(v string) {
	o.TransFrom = v
}

// GetTransTo returns the TransTo field value
func (o *MarginTransferDetailsRows) GetTransTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransTo
}

// GetTransToOk returns a tuple with the TransTo field value
// and a boolean to check if the value has been set.
func (o *MarginTransferDetailsRows) GetTransToOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TransTo, true
}

// SetTransTo sets field value
func (o *MarginTransferDetailsRows) SetTransTo(v string) {
	o.TransTo = v
}

func (o MarginTransferDetailsRows) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["amount"] = o.Amount
	}
	if true {
		toSerialize["asset"] = o.Asset
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if true {
		toSerialize["timestamp"] = o.Timestamp
	}
	if true {
		toSerialize["txId"] = o.TxId
	}
	if true {
		toSerialize["transFrom"] = o.TransFrom
	}
	if true {
		toSerialize["transTo"] = o.TransTo
	}
	return json.Marshal(toSerialize)
}

type NullableMarginTransferDetailsRows struct {
	value *MarginTransferDetailsRows
	isSet bool
}

func (v NullableMarginTransferDetailsRows) Get() *MarginTransferDetailsRows {
	return v.value
}

func (v *NullableMarginTransferDetailsRows) Set(val *MarginTransferDetailsRows) {
	v.value = val
	v.isSet = true
}

func (v NullableMarginTransferDetailsRows) IsSet() bool {
	return v.isSet
}

func (v *NullableMarginTransferDetailsRows) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMarginTransferDetailsRows(val *MarginTransferDetailsRows) *NullableMarginTransferDetailsRows {
	return &NullableMarginTransferDetailsRows{value: val, isSet: true}
}

func (v NullableMarginTransferDetailsRows) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMarginTransferDetailsRows) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


