/*
Binance Public Spot API

OpenAPI Specifications for the Binance Public Spot API generated with [binance/binance-api-swagger/blob/master/spot_api.yaml](https://github.com/binance/binance-api-swagger/blob/master/spot_api.yaml) with commit [v1.2.0 release](https://github.com/binance/binance-api-swagger/commit/60d14be031c031600c853d5cdab86db5ab73603e)  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)

API version: 1.0
Contact: qishiwenjun@163.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package binanceapi

import (
	"encoding/json"
)

// CoinInfo struct for CoinInfo
type CoinInfo struct {
	Coin              string                           `json:"coin"`
	DepositAllEnable  bool                             `json:"depositAllEnable"`
	Free              string                           `json:"free"`
	Freeze            string                           `json:"freeze"`
	Ipoable           string                           `json:"ipoable"`
	Ipoing            string                           `json:"ipoing"`
	IsLegalMoney      bool                             `json:"isLegalMoney"`
	Locked            string                           `json:"locked"`
	Name              string                           `json:"name"`
	NetworkList       []CapitalConfigGetallNetworkList `json:"networkList"`
	Storage           string                           `json:"storage"`
	Trading           bool                             `json:"trading"`
	WithdrawAllEnable bool                             `json:"withdrawAllEnable"`
	Withdrawing       string                           `json:"withdrawing"`
}

// NewCoinInfo instantiates a new CoinInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoinInfo(coin string, depositAllEnable bool, free string, freeze string, ipoable string, ipoing string, isLegalMoney bool, locked string, name string, networkList []CapitalConfigGetallNetworkList, storage string, trading bool, withdrawAllEnable bool, withdrawing string) *CoinInfo {
	this := CoinInfo{}
	this.Coin = coin
	this.DepositAllEnable = depositAllEnable
	this.Free = free
	this.Freeze = freeze
	this.Ipoable = ipoable
	this.Ipoing = ipoing
	this.IsLegalMoney = isLegalMoney
	this.Locked = locked
	this.Name = name
	this.NetworkList = networkList
	this.Storage = storage
	this.Trading = trading
	this.WithdrawAllEnable = withdrawAllEnable
	this.Withdrawing = withdrawing
	return &this
}

// NewCoinInfoWithDefaults instantiates a new CoinInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoinInfoWithDefaults() *CoinInfo {
	this := CoinInfo{}
	return &this
}

// GetCoin returns the Coin field value
func (o *CoinInfo) GetCoin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Coin
}

// GetCoinOk returns a tuple with the Coin field value
// and a boolean to check if the value has been set.
func (o *CoinInfo) GetCoinOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Coin, true
}

// SetCoin sets field value
func (o *CoinInfo) SetCoin(v string) {
	o.Coin = v
}

// GetDepositAllEnable returns the DepositAllEnable field value
func (o *CoinInfo) GetDepositAllEnable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DepositAllEnable
}

// GetDepositAllEnableOk returns a tuple with the DepositAllEnable field value
// and a boolean to check if the value has been set.
func (o *CoinInfo) GetDepositAllEnableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DepositAllEnable, true
}

// SetDepositAllEnable sets field value
func (o *CoinInfo) SetDepositAllEnable(v bool) {
	o.DepositAllEnable = v
}

// GetFree returns the Free field value
func (o *CoinInfo) GetFree() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Free
}

// GetFreeOk returns a tuple with the Free field value
// and a boolean to check if the value has been set.
func (o *CoinInfo) GetFreeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Free, true
}

// SetFree sets field value
func (o *CoinInfo) SetFree(v string) {
	o.Free = v
}

// GetFreeze returns the Freeze field value
func (o *CoinInfo) GetFreeze() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Freeze
}

// GetFreezeOk returns a tuple with the Freeze field value
// and a boolean to check if the value has been set.
func (o *CoinInfo) GetFreezeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Freeze, true
}

// SetFreeze sets field value
func (o *CoinInfo) SetFreeze(v string) {
	o.Freeze = v
}

// GetIpoable returns the Ipoable field value
func (o *CoinInfo) GetIpoable() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ipoable
}

// GetIpoableOk returns a tuple with the Ipoable field value
// and a boolean to check if the value has been set.
func (o *CoinInfo) GetIpoableOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ipoable, true
}

// SetIpoable sets field value
func (o *CoinInfo) SetIpoable(v string) {
	o.Ipoable = v
}

// GetIpoing returns the Ipoing field value
func (o *CoinInfo) GetIpoing() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ipoing
}

// GetIpoingOk returns a tuple with the Ipoing field value
// and a boolean to check if the value has been set.
func (o *CoinInfo) GetIpoingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ipoing, true
}

// SetIpoing sets field value
func (o *CoinInfo) SetIpoing(v string) {
	o.Ipoing = v
}

// GetIsLegalMoney returns the IsLegalMoney field value
func (o *CoinInfo) GetIsLegalMoney() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsLegalMoney
}

// GetIsLegalMoneyOk returns a tuple with the IsLegalMoney field value
// and a boolean to check if the value has been set.
func (o *CoinInfo) GetIsLegalMoneyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsLegalMoney, true
}

// SetIsLegalMoney sets field value
func (o *CoinInfo) SetIsLegalMoney(v bool) {
	o.IsLegalMoney = v
}

// GetLocked returns the Locked field value
func (o *CoinInfo) GetLocked() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Locked
}

// GetLockedOk returns a tuple with the Locked field value
// and a boolean to check if the value has been set.
func (o *CoinInfo) GetLockedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Locked, true
}

// SetLocked sets field value
func (o *CoinInfo) SetLocked(v string) {
	o.Locked = v
}

// GetName returns the Name field value
func (o *CoinInfo) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CoinInfo) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CoinInfo) SetName(v string) {
	o.Name = v
}

// GetNetworkList returns the NetworkList field value
func (o *CoinInfo) GetNetworkList() []CapitalConfigGetallNetworkList {
	if o == nil {
		var ret []CapitalConfigGetallNetworkList
		return ret
	}

	return o.NetworkList
}

// GetNetworkListOk returns a tuple with the NetworkList field value
// and a boolean to check if the value has been set.
func (o *CoinInfo) GetNetworkListOk() (*[]CapitalConfigGetallNetworkList, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetworkList, true
}

// SetNetworkList sets field value
func (o *CoinInfo) SetNetworkList(v []CapitalConfigGetallNetworkList) {
	o.NetworkList = v
}

// GetStorage returns the Storage field value
func (o *CoinInfo) GetStorage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Storage
}

// GetStorageOk returns a tuple with the Storage field value
// and a boolean to check if the value has been set.
func (o *CoinInfo) GetStorageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Storage, true
}

// SetStorage sets field value
func (o *CoinInfo) SetStorage(v string) {
	o.Storage = v
}

// GetTrading returns the Trading field value
func (o *CoinInfo) GetTrading() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Trading
}

// GetTradingOk returns a tuple with the Trading field value
// and a boolean to check if the value has been set.
func (o *CoinInfo) GetTradingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Trading, true
}

// SetTrading sets field value
func (o *CoinInfo) SetTrading(v bool) {
	o.Trading = v
}

// GetWithdrawAllEnable returns the WithdrawAllEnable field value
func (o *CoinInfo) GetWithdrawAllEnable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.WithdrawAllEnable
}

// GetWithdrawAllEnableOk returns a tuple with the WithdrawAllEnable field value
// and a boolean to check if the value has been set.
func (o *CoinInfo) GetWithdrawAllEnableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WithdrawAllEnable, true
}

// SetWithdrawAllEnable sets field value
func (o *CoinInfo) SetWithdrawAllEnable(v bool) {
	o.WithdrawAllEnable = v
}

// GetWithdrawing returns the Withdrawing field value
func (o *CoinInfo) GetWithdrawing() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Withdrawing
}

// GetWithdrawingOk returns a tuple with the Withdrawing field value
// and a boolean to check if the value has been set.
func (o *CoinInfo) GetWithdrawingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Withdrawing, true
}

// SetWithdrawing sets field value
func (o *CoinInfo) SetWithdrawing(v string) {
	o.Withdrawing = v
}

func (o CoinInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["coin"] = o.Coin
	}
	if true {
		toSerialize["depositAllEnable"] = o.DepositAllEnable
	}
	if true {
		toSerialize["free"] = o.Free
	}
	if true {
		toSerialize["freeze"] = o.Freeze
	}
	if true {
		toSerialize["ipoable"] = o.Ipoable
	}
	if true {
		toSerialize["ipoing"] = o.Ipoing
	}
	if true {
		toSerialize["isLegalMoney"] = o.IsLegalMoney
	}
	if true {
		toSerialize["locked"] = o.Locked
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["networkList"] = o.NetworkList
	}
	if true {
		toSerialize["storage"] = o.Storage
	}
	if true {
		toSerialize["trading"] = o.Trading
	}
	if true {
		toSerialize["withdrawAllEnable"] = o.WithdrawAllEnable
	}
	if true {
		toSerialize["withdrawing"] = o.Withdrawing
	}
	return json.Marshal(toSerialize)
}

type NullableCoinInfo struct {
	value *CoinInfo
	isSet bool
}

func (v NullableCoinInfo) Get() *CoinInfo {
	return v.value
}

func (v *NullableCoinInfo) Set(val *CoinInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableCoinInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableCoinInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoinInfo(val *CoinInfo) *NullableCoinInfo {
	return &NullableCoinInfo{value: val, isSet: true}
}

func (v NullableCoinInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoinInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
