/*
Binance Public Spot API

OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package binanceapi

import (
	"encoding/json"
)

// SapiV1CapitalConfigGetallNetworkList struct for SapiV1CapitalConfigGetallNetworkList
type SapiV1CapitalConfigGetallNetworkList struct {
	AddressRegex string `json:"addressRegex"`
	Coin string `json:"coin"`
	// shown only when \"depositEnable\" is false.
	DepositDesc string `json:"depositDesc"`
	DepositEnable bool `json:"depositEnable"`
	IsDefault bool `json:"isDefault"`
	MemoRegex string `json:"memoRegex"`
	// min number for balance confirmation.
	MinConfirm int64 `json:"minConfirm"`
	Name string `json:"name"`
	ResetAddressStatus bool `json:"resetAddressStatus"`
	SpecialTips string `json:"specialTips"`
	// confirmation number for balance unlock.
	UnLockConfirm int64 `json:"unLockConfirm"`
	// shown only when \"withdrawEnable\" is false
	WithdrawDesc string `json:"withdrawDesc"`
	WithdrawEnable bool `json:"withdrawEnable"`
	WithdrawFee string `json:"withdrawFee"`
	WithdrawIntegerMultiple string `json:"withdrawIntegerMultiple"`
	WithdrawMax string `json:"withdrawMax"`
	WithdrawMin string `json:"withdrawMin"`
	SameAddress bool `json:"sameAddress"`
}

// NewSapiV1CapitalConfigGetallNetworkList instantiates a new SapiV1CapitalConfigGetallNetworkList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSapiV1CapitalConfigGetallNetworkList(addressRegex string, coin string, depositDesc string, depositEnable bool, isDefault bool, memoRegex string, minConfirm int64, name string, resetAddressStatus bool, specialTips string, unLockConfirm int64, withdrawDesc string, withdrawEnable bool, withdrawFee string, withdrawIntegerMultiple string, withdrawMax string, withdrawMin string, sameAddress bool) *SapiV1CapitalConfigGetallNetworkList {
	this := SapiV1CapitalConfigGetallNetworkList{}
	this.AddressRegex = addressRegex
	this.Coin = coin
	this.DepositDesc = depositDesc
	this.DepositEnable = depositEnable
	this.IsDefault = isDefault
	this.MemoRegex = memoRegex
	this.MinConfirm = minConfirm
	this.Name = name
	this.ResetAddressStatus = resetAddressStatus
	this.SpecialTips = specialTips
	this.UnLockConfirm = unLockConfirm
	this.WithdrawDesc = withdrawDesc
	this.WithdrawEnable = withdrawEnable
	this.WithdrawFee = withdrawFee
	this.WithdrawIntegerMultiple = withdrawIntegerMultiple
	this.WithdrawMax = withdrawMax
	this.WithdrawMin = withdrawMin
	this.SameAddress = sameAddress
	return &this
}

// NewSapiV1CapitalConfigGetallNetworkListWithDefaults instantiates a new SapiV1CapitalConfigGetallNetworkList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSapiV1CapitalConfigGetallNetworkListWithDefaults() *SapiV1CapitalConfigGetallNetworkList {
	this := SapiV1CapitalConfigGetallNetworkList{}
	return &this
}

// GetAddressRegex returns the AddressRegex field value
func (o *SapiV1CapitalConfigGetallNetworkList) GetAddressRegex() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AddressRegex
}

// GetAddressRegexOk returns a tuple with the AddressRegex field value
// and a boolean to check if the value has been set.
func (o *SapiV1CapitalConfigGetallNetworkList) GetAddressRegexOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AddressRegex, true
}

// SetAddressRegex sets field value
func (o *SapiV1CapitalConfigGetallNetworkList) SetAddressRegex(v string) {
	o.AddressRegex = v
}

// GetCoin returns the Coin field value
func (o *SapiV1CapitalConfigGetallNetworkList) GetCoin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Coin
}

// GetCoinOk returns a tuple with the Coin field value
// and a boolean to check if the value has been set.
func (o *SapiV1CapitalConfigGetallNetworkList) GetCoinOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Coin, true
}

// SetCoin sets field value
func (o *SapiV1CapitalConfigGetallNetworkList) SetCoin(v string) {
	o.Coin = v
}

// GetDepositDesc returns the DepositDesc field value
func (o *SapiV1CapitalConfigGetallNetworkList) GetDepositDesc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DepositDesc
}

// GetDepositDescOk returns a tuple with the DepositDesc field value
// and a boolean to check if the value has been set.
func (o *SapiV1CapitalConfigGetallNetworkList) GetDepositDescOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DepositDesc, true
}

// SetDepositDesc sets field value
func (o *SapiV1CapitalConfigGetallNetworkList) SetDepositDesc(v string) {
	o.DepositDesc = v
}

// GetDepositEnable returns the DepositEnable field value
func (o *SapiV1CapitalConfigGetallNetworkList) GetDepositEnable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DepositEnable
}

// GetDepositEnableOk returns a tuple with the DepositEnable field value
// and a boolean to check if the value has been set.
func (o *SapiV1CapitalConfigGetallNetworkList) GetDepositEnableOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DepositEnable, true
}

// SetDepositEnable sets field value
func (o *SapiV1CapitalConfigGetallNetworkList) SetDepositEnable(v bool) {
	o.DepositEnable = v
}

// GetIsDefault returns the IsDefault field value
func (o *SapiV1CapitalConfigGetallNetworkList) GetIsDefault() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsDefault
}

// GetIsDefaultOk returns a tuple with the IsDefault field value
// and a boolean to check if the value has been set.
func (o *SapiV1CapitalConfigGetallNetworkList) GetIsDefaultOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.IsDefault, true
}

// SetIsDefault sets field value
func (o *SapiV1CapitalConfigGetallNetworkList) SetIsDefault(v bool) {
	o.IsDefault = v
}

// GetMemoRegex returns the MemoRegex field value
func (o *SapiV1CapitalConfigGetallNetworkList) GetMemoRegex() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MemoRegex
}

// GetMemoRegexOk returns a tuple with the MemoRegex field value
// and a boolean to check if the value has been set.
func (o *SapiV1CapitalConfigGetallNetworkList) GetMemoRegexOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.MemoRegex, true
}

// SetMemoRegex sets field value
func (o *SapiV1CapitalConfigGetallNetworkList) SetMemoRegex(v string) {
	o.MemoRegex = v
}

// GetMinConfirm returns the MinConfirm field value
func (o *SapiV1CapitalConfigGetallNetworkList) GetMinConfirm() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MinConfirm
}

// GetMinConfirmOk returns a tuple with the MinConfirm field value
// and a boolean to check if the value has been set.
func (o *SapiV1CapitalConfigGetallNetworkList) GetMinConfirmOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.MinConfirm, true
}

// SetMinConfirm sets field value
func (o *SapiV1CapitalConfigGetallNetworkList) SetMinConfirm(v int64) {
	o.MinConfirm = v
}

// GetName returns the Name field value
func (o *SapiV1CapitalConfigGetallNetworkList) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SapiV1CapitalConfigGetallNetworkList) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SapiV1CapitalConfigGetallNetworkList) SetName(v string) {
	o.Name = v
}

// GetResetAddressStatus returns the ResetAddressStatus field value
func (o *SapiV1CapitalConfigGetallNetworkList) GetResetAddressStatus() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ResetAddressStatus
}

// GetResetAddressStatusOk returns a tuple with the ResetAddressStatus field value
// and a boolean to check if the value has been set.
func (o *SapiV1CapitalConfigGetallNetworkList) GetResetAddressStatusOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ResetAddressStatus, true
}

// SetResetAddressStatus sets field value
func (o *SapiV1CapitalConfigGetallNetworkList) SetResetAddressStatus(v bool) {
	o.ResetAddressStatus = v
}

// GetSpecialTips returns the SpecialTips field value
func (o *SapiV1CapitalConfigGetallNetworkList) GetSpecialTips() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SpecialTips
}

// GetSpecialTipsOk returns a tuple with the SpecialTips field value
// and a boolean to check if the value has been set.
func (o *SapiV1CapitalConfigGetallNetworkList) GetSpecialTipsOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SpecialTips, true
}

// SetSpecialTips sets field value
func (o *SapiV1CapitalConfigGetallNetworkList) SetSpecialTips(v string) {
	o.SpecialTips = v
}

// GetUnLockConfirm returns the UnLockConfirm field value
func (o *SapiV1CapitalConfigGetallNetworkList) GetUnLockConfirm() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UnLockConfirm
}

// GetUnLockConfirmOk returns a tuple with the UnLockConfirm field value
// and a boolean to check if the value has been set.
func (o *SapiV1CapitalConfigGetallNetworkList) GetUnLockConfirmOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UnLockConfirm, true
}

// SetUnLockConfirm sets field value
func (o *SapiV1CapitalConfigGetallNetworkList) SetUnLockConfirm(v int64) {
	o.UnLockConfirm = v
}

// GetWithdrawDesc returns the WithdrawDesc field value
func (o *SapiV1CapitalConfigGetallNetworkList) GetWithdrawDesc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WithdrawDesc
}

// GetWithdrawDescOk returns a tuple with the WithdrawDesc field value
// and a boolean to check if the value has been set.
func (o *SapiV1CapitalConfigGetallNetworkList) GetWithdrawDescOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.WithdrawDesc, true
}

// SetWithdrawDesc sets field value
func (o *SapiV1CapitalConfigGetallNetworkList) SetWithdrawDesc(v string) {
	o.WithdrawDesc = v
}

// GetWithdrawEnable returns the WithdrawEnable field value
func (o *SapiV1CapitalConfigGetallNetworkList) GetWithdrawEnable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.WithdrawEnable
}

// GetWithdrawEnableOk returns a tuple with the WithdrawEnable field value
// and a boolean to check if the value has been set.
func (o *SapiV1CapitalConfigGetallNetworkList) GetWithdrawEnableOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.WithdrawEnable, true
}

// SetWithdrawEnable sets field value
func (o *SapiV1CapitalConfigGetallNetworkList) SetWithdrawEnable(v bool) {
	o.WithdrawEnable = v
}

// GetWithdrawFee returns the WithdrawFee field value
func (o *SapiV1CapitalConfigGetallNetworkList) GetWithdrawFee() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WithdrawFee
}

// GetWithdrawFeeOk returns a tuple with the WithdrawFee field value
// and a boolean to check if the value has been set.
func (o *SapiV1CapitalConfigGetallNetworkList) GetWithdrawFeeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.WithdrawFee, true
}

// SetWithdrawFee sets field value
func (o *SapiV1CapitalConfigGetallNetworkList) SetWithdrawFee(v string) {
	o.WithdrawFee = v
}

// GetWithdrawIntegerMultiple returns the WithdrawIntegerMultiple field value
func (o *SapiV1CapitalConfigGetallNetworkList) GetWithdrawIntegerMultiple() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WithdrawIntegerMultiple
}

// GetWithdrawIntegerMultipleOk returns a tuple with the WithdrawIntegerMultiple field value
// and a boolean to check if the value has been set.
func (o *SapiV1CapitalConfigGetallNetworkList) GetWithdrawIntegerMultipleOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.WithdrawIntegerMultiple, true
}

// SetWithdrawIntegerMultiple sets field value
func (o *SapiV1CapitalConfigGetallNetworkList) SetWithdrawIntegerMultiple(v string) {
	o.WithdrawIntegerMultiple = v
}

// GetWithdrawMax returns the WithdrawMax field value
func (o *SapiV1CapitalConfigGetallNetworkList) GetWithdrawMax() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WithdrawMax
}

// GetWithdrawMaxOk returns a tuple with the WithdrawMax field value
// and a boolean to check if the value has been set.
func (o *SapiV1CapitalConfigGetallNetworkList) GetWithdrawMaxOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.WithdrawMax, true
}

// SetWithdrawMax sets field value
func (o *SapiV1CapitalConfigGetallNetworkList) SetWithdrawMax(v string) {
	o.WithdrawMax = v
}

// GetWithdrawMin returns the WithdrawMin field value
func (o *SapiV1CapitalConfigGetallNetworkList) GetWithdrawMin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WithdrawMin
}

// GetWithdrawMinOk returns a tuple with the WithdrawMin field value
// and a boolean to check if the value has been set.
func (o *SapiV1CapitalConfigGetallNetworkList) GetWithdrawMinOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.WithdrawMin, true
}

// SetWithdrawMin sets field value
func (o *SapiV1CapitalConfigGetallNetworkList) SetWithdrawMin(v string) {
	o.WithdrawMin = v
}

// GetSameAddress returns the SameAddress field value
func (o *SapiV1CapitalConfigGetallNetworkList) GetSameAddress() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.SameAddress
}

// GetSameAddressOk returns a tuple with the SameAddress field value
// and a boolean to check if the value has been set.
func (o *SapiV1CapitalConfigGetallNetworkList) GetSameAddressOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SameAddress, true
}

// SetSameAddress sets field value
func (o *SapiV1CapitalConfigGetallNetworkList) SetSameAddress(v bool) {
	o.SameAddress = v
}

func (o SapiV1CapitalConfigGetallNetworkList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["addressRegex"] = o.AddressRegex
	}
	if true {
		toSerialize["coin"] = o.Coin
	}
	if true {
		toSerialize["depositDesc"] = o.DepositDesc
	}
	if true {
		toSerialize["depositEnable"] = o.DepositEnable
	}
	if true {
		toSerialize["isDefault"] = o.IsDefault
	}
	if true {
		toSerialize["memoRegex"] = o.MemoRegex
	}
	if true {
		toSerialize["minConfirm"] = o.MinConfirm
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["resetAddressStatus"] = o.ResetAddressStatus
	}
	if true {
		toSerialize["specialTips"] = o.SpecialTips
	}
	if true {
		toSerialize["unLockConfirm"] = o.UnLockConfirm
	}
	if true {
		toSerialize["withdrawDesc"] = o.WithdrawDesc
	}
	if true {
		toSerialize["withdrawEnable"] = o.WithdrawEnable
	}
	if true {
		toSerialize["withdrawFee"] = o.WithdrawFee
	}
	if true {
		toSerialize["withdrawIntegerMultiple"] = o.WithdrawIntegerMultiple
	}
	if true {
		toSerialize["withdrawMax"] = o.WithdrawMax
	}
	if true {
		toSerialize["withdrawMin"] = o.WithdrawMin
	}
	if true {
		toSerialize["sameAddress"] = o.SameAddress
	}
	return json.Marshal(toSerialize)
}

type NullableSapiV1CapitalConfigGetallNetworkList struct {
	value *SapiV1CapitalConfigGetallNetworkList
	isSet bool
}

func (v NullableSapiV1CapitalConfigGetallNetworkList) Get() *SapiV1CapitalConfigGetallNetworkList {
	return v.value
}

func (v *NullableSapiV1CapitalConfigGetallNetworkList) Set(val *SapiV1CapitalConfigGetallNetworkList) {
	v.value = val
	v.isSet = true
}

func (v NullableSapiV1CapitalConfigGetallNetworkList) IsSet() bool {
	return v.isSet
}

func (v *NullableSapiV1CapitalConfigGetallNetworkList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSapiV1CapitalConfigGetallNetworkList(val *SapiV1CapitalConfigGetallNetworkList) *NullableSapiV1CapitalConfigGetallNetworkList {
	return &NullableSapiV1CapitalConfigGetallNetworkList{value: val, isSet: true}
}

func (v NullableSapiV1CapitalConfigGetallNetworkList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSapiV1CapitalConfigGetallNetworkList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


