/*
Binance Public Spot API

OpenAPI Specifications for the Binance Public Spot API generated with [binance/binance-api-swagger/blob/master/spot_api.yaml](https://github.com/binance/binance-api-swagger/blob/master/spot_api.yaml) with commit [v1.2.0 release](https://github.com/binance/binance-api-swagger/commit/60d14be031c031600c853d5cdab86db5ab73603e)  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)

API version: 1.0
Contact: qishiwenjun@163.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package binanceapi

import (
	"encoding/json"
)

// MarginOrderResponseAck struct for MarginOrderResponseAck
type MarginOrderResponseAck struct {
	Symbol        string `json:"symbol"`
	OrderId       int64  `json:"orderId"`
	ClientOrderId string `json:"clientOrderId"`
	IsIsolated    bool   `json:"isIsolated"`
	TransactTime  int64  `json:"transactTime"`
}

// NewMarginOrderResponseAck instantiates a new MarginOrderResponseAck object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMarginOrderResponseAck(symbol string, orderId int64, clientOrderId string, isIsolated bool, transactTime int64) *MarginOrderResponseAck {
	this := MarginOrderResponseAck{}
	this.Symbol = symbol
	this.OrderId = orderId
	this.ClientOrderId = clientOrderId
	this.IsIsolated = isIsolated
	this.TransactTime = transactTime
	return &this
}

// NewMarginOrderResponseAckWithDefaults instantiates a new MarginOrderResponseAck object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMarginOrderResponseAckWithDefaults() *MarginOrderResponseAck {
	this := MarginOrderResponseAck{}
	return &this
}

// GetSymbol returns the Symbol field value
func (o *MarginOrderResponseAck) GetSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value
// and a boolean to check if the value has been set.
func (o *MarginOrderResponseAck) GetSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Symbol, true
}

// SetSymbol sets field value
func (o *MarginOrderResponseAck) SetSymbol(v string) {
	o.Symbol = v
}

// GetOrderId returns the OrderId field value
func (o *MarginOrderResponseAck) GetOrderId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value
// and a boolean to check if the value has been set.
func (o *MarginOrderResponseAck) GetOrderIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderId, true
}

// SetOrderId sets field value
func (o *MarginOrderResponseAck) SetOrderId(v int64) {
	o.OrderId = v
}

// GetClientOrderId returns the ClientOrderId field value
func (o *MarginOrderResponseAck) GetClientOrderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientOrderId
}

// GetClientOrderIdOk returns a tuple with the ClientOrderId field value
// and a boolean to check if the value has been set.
func (o *MarginOrderResponseAck) GetClientOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientOrderId, true
}

// SetClientOrderId sets field value
func (o *MarginOrderResponseAck) SetClientOrderId(v string) {
	o.ClientOrderId = v
}

// GetIsIsolated returns the IsIsolated field value
func (o *MarginOrderResponseAck) GetIsIsolated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsIsolated
}

// GetIsIsolatedOk returns a tuple with the IsIsolated field value
// and a boolean to check if the value has been set.
func (o *MarginOrderResponseAck) GetIsIsolatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsIsolated, true
}

// SetIsIsolated sets field value
func (o *MarginOrderResponseAck) SetIsIsolated(v bool) {
	o.IsIsolated = v
}

// GetTransactTime returns the TransactTime field value
func (o *MarginOrderResponseAck) GetTransactTime() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TransactTime
}

// GetTransactTimeOk returns a tuple with the TransactTime field value
// and a boolean to check if the value has been set.
func (o *MarginOrderResponseAck) GetTransactTimeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactTime, true
}

// SetTransactTime sets field value
func (o *MarginOrderResponseAck) SetTransactTime(v int64) {
	o.TransactTime = v
}

func (o MarginOrderResponseAck) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["symbol"] = o.Symbol
	}
	if true {
		toSerialize["orderId"] = o.OrderId
	}
	if true {
		toSerialize["clientOrderId"] = o.ClientOrderId
	}
	if true {
		toSerialize["isIsolated"] = o.IsIsolated
	}
	if true {
		toSerialize["transactTime"] = o.TransactTime
	}
	return json.Marshal(toSerialize)
}

type NullableMarginOrderResponseAck struct {
	value *MarginOrderResponseAck
	isSet bool
}

func (v NullableMarginOrderResponseAck) Get() *MarginOrderResponseAck {
	return v.value
}

func (v *NullableMarginOrderResponseAck) Set(val *MarginOrderResponseAck) {
	v.value = val
	v.isSet = true
}

func (v NullableMarginOrderResponseAck) IsSet() bool {
	return v.isSet
}

func (v *NullableMarginOrderResponseAck) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMarginOrderResponseAck(val *MarginOrderResponseAck) *NullableMarginOrderResponseAck {
	return &NullableMarginOrderResponseAck{value: val, isSet: true}
}

func (v NullableMarginOrderResponseAck) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMarginOrderResponseAck) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
