/*
Binance Public Spot API

OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineResponse20048 struct for InlineResponse20048
type InlineResponse20048 struct {
	From string `json:"from"`
	To string `json:"to"`
	Asset string `json:"asset"`
	Qty string `json:"qty"`
	Status string `json:"status"`
	TranId int64 `json:"tranId"`
	Time int64 `json:"time"`
}

// NewInlineResponse20048 instantiates a new InlineResponse20048 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20048(from string, to string, asset string, qty string, status string, tranId int64, time int64) *InlineResponse20048 {
	this := InlineResponse20048{}
	this.From = from
	this.To = to
	this.Asset = asset
	this.Qty = qty
	this.Status = status
	this.TranId = tranId
	this.Time = time
	return &this
}

// NewInlineResponse20048WithDefaults instantiates a new InlineResponse20048 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20048WithDefaults() *InlineResponse20048 {
	this := InlineResponse20048{}
	return &this
}

// GetFrom returns the From field value
func (o *InlineResponse20048) GetFrom() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20048) GetFromOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *InlineResponse20048) SetFrom(v string) {
	o.From = v
}

// GetTo returns the To field value
func (o *InlineResponse20048) GetTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20048) GetToOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *InlineResponse20048) SetTo(v string) {
	o.To = v
}

// GetAsset returns the Asset field value
func (o *InlineResponse20048) GetAsset() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Asset
}

// GetAssetOk returns a tuple with the Asset field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20048) GetAssetOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Asset, true
}

// SetAsset sets field value
func (o *InlineResponse20048) SetAsset(v string) {
	o.Asset = v
}

// GetQty returns the Qty field value
func (o *InlineResponse20048) GetQty() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Qty
}

// GetQtyOk returns a tuple with the Qty field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20048) GetQtyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Qty, true
}

// SetQty sets field value
func (o *InlineResponse20048) SetQty(v string) {
	o.Qty = v
}

// GetStatus returns the Status field value
func (o *InlineResponse20048) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20048) GetStatusOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *InlineResponse20048) SetStatus(v string) {
	o.Status = v
}

// GetTranId returns the TranId field value
func (o *InlineResponse20048) GetTranId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TranId
}

// GetTranIdOk returns a tuple with the TranId field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20048) GetTranIdOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TranId, true
}

// SetTranId sets field value
func (o *InlineResponse20048) SetTranId(v int64) {
	o.TranId = v
}

// GetTime returns the Time field value
func (o *InlineResponse20048) GetTime() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Time
}

// GetTimeOk returns a tuple with the Time field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20048) GetTimeOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Time, true
}

// SetTime sets field value
func (o *InlineResponse20048) SetTime(v int64) {
	o.Time = v
}

func (o InlineResponse20048) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["from"] = o.From
	}
	if true {
		toSerialize["to"] = o.To
	}
	if true {
		toSerialize["asset"] = o.Asset
	}
	if true {
		toSerialize["qty"] = o.Qty
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if true {
		toSerialize["tranId"] = o.TranId
	}
	if true {
		toSerialize["time"] = o.Time
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20048 struct {
	value *InlineResponse20048
	isSet bool
}

func (v NullableInlineResponse20048) Get() *InlineResponse20048 {
	return v.value
}

func (v *NullableInlineResponse20048) Set(val *InlineResponse20048) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20048) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20048) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20048(val *InlineResponse20048) *NullableInlineResponse20048 {
	return &NullableInlineResponse20048{value: val, isSet: true}
}

func (v NullableInlineResponse20048) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20048) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


