/*
Binance Public Spot API

OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package binanceapi

import (
	"encoding/json"
)

// InlineResponse20017Rows struct for InlineResponse20017Rows
type InlineResponse20017Rows struct {
	IsolatedSymbol string `json:"isolatedSymbol"`
	Asset string `json:"asset"`
	Interest string `json:"interest"`
	InterestAccuredTime int64 `json:"interestAccuredTime"`
	InterestRate string `json:"interestRate"`
	Principal string `json:"principal"`
	Type string `json:"type"`
}

// NewInlineResponse20017Rows instantiates a new InlineResponse20017Rows object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20017Rows(isolatedSymbol string, asset string, interest string, interestAccuredTime int64, interestRate string, principal string, type_ string) *InlineResponse20017Rows {
	this := InlineResponse20017Rows{}
	this.IsolatedSymbol = isolatedSymbol
	this.Asset = asset
	this.Interest = interest
	this.InterestAccuredTime = interestAccuredTime
	this.InterestRate = interestRate
	this.Principal = principal
	this.Type = type_
	return &this
}

// NewInlineResponse20017RowsWithDefaults instantiates a new InlineResponse20017Rows object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20017RowsWithDefaults() *InlineResponse20017Rows {
	this := InlineResponse20017Rows{}
	return &this
}

// GetIsolatedSymbol returns the IsolatedSymbol field value
func (o *InlineResponse20017Rows) GetIsolatedSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IsolatedSymbol
}

// GetIsolatedSymbolOk returns a tuple with the IsolatedSymbol field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20017Rows) GetIsolatedSymbolOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.IsolatedSymbol, true
}

// SetIsolatedSymbol sets field value
func (o *InlineResponse20017Rows) SetIsolatedSymbol(v string) {
	o.IsolatedSymbol = v
}

// GetAsset returns the Asset field value
func (o *InlineResponse20017Rows) GetAsset() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Asset
}

// GetAssetOk returns a tuple with the Asset field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20017Rows) GetAssetOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Asset, true
}

// SetAsset sets field value
func (o *InlineResponse20017Rows) SetAsset(v string) {
	o.Asset = v
}

// GetInterest returns the Interest field value
func (o *InlineResponse20017Rows) GetInterest() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Interest
}

// GetInterestOk returns a tuple with the Interest field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20017Rows) GetInterestOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Interest, true
}

// SetInterest sets field value
func (o *InlineResponse20017Rows) SetInterest(v string) {
	o.Interest = v
}

// GetInterestAccuredTime returns the InterestAccuredTime field value
func (o *InlineResponse20017Rows) GetInterestAccuredTime() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.InterestAccuredTime
}

// GetInterestAccuredTimeOk returns a tuple with the InterestAccuredTime field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20017Rows) GetInterestAccuredTimeOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.InterestAccuredTime, true
}

// SetInterestAccuredTime sets field value
func (o *InlineResponse20017Rows) SetInterestAccuredTime(v int64) {
	o.InterestAccuredTime = v
}

// GetInterestRate returns the InterestRate field value
func (o *InlineResponse20017Rows) GetInterestRate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InterestRate
}

// GetInterestRateOk returns a tuple with the InterestRate field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20017Rows) GetInterestRateOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.InterestRate, true
}

// SetInterestRate sets field value
func (o *InlineResponse20017Rows) SetInterestRate(v string) {
	o.InterestRate = v
}

// GetPrincipal returns the Principal field value
func (o *InlineResponse20017Rows) GetPrincipal() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Principal
}

// GetPrincipalOk returns a tuple with the Principal field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20017Rows) GetPrincipalOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Principal, true
}

// SetPrincipal sets field value
func (o *InlineResponse20017Rows) SetPrincipal(v string) {
	o.Principal = v
}

// GetType returns the Type field value
func (o *InlineResponse20017Rows) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20017Rows) GetTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *InlineResponse20017Rows) SetType(v string) {
	o.Type = v
}

func (o InlineResponse20017Rows) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["isolatedSymbol"] = o.IsolatedSymbol
	}
	if true {
		toSerialize["asset"] = o.Asset
	}
	if true {
		toSerialize["interest"] = o.Interest
	}
	if true {
		toSerialize["interestAccuredTime"] = o.InterestAccuredTime
	}
	if true {
		toSerialize["interestRate"] = o.InterestRate
	}
	if true {
		toSerialize["principal"] = o.Principal
	}
	if true {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20017Rows struct {
	value *InlineResponse20017Rows
	isSet bool
}

func (v NullableInlineResponse20017Rows) Get() *InlineResponse20017Rows {
	return v.value
}

func (v *NullableInlineResponse20017Rows) Set(val *InlineResponse20017Rows) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20017Rows) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20017Rows) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20017Rows(val *InlineResponse20017Rows) *NullableInlineResponse20017Rows {
	return &NullableInlineResponse20017Rows{value: val, isSet: true}
}

func (v NullableInlineResponse20017Rows) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20017Rows) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


