/*
Binance Public Spot API

OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineResponse20092Data struct for InlineResponse20092Data
type InlineResponse20092Data struct {
	ProfitTransferDetails []InlineResponse20092DataProfitTransferDetails `json:"profitTransferDetails"`
	TotalNum int64 `json:"totalNum"`
	PageSize int64 `json:"pageSize"`
}

// NewInlineResponse20092Data instantiates a new InlineResponse20092Data object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20092Data(profitTransferDetails []InlineResponse20092DataProfitTransferDetails, totalNum int64, pageSize int64) *InlineResponse20092Data {
	this := InlineResponse20092Data{}
	this.ProfitTransferDetails = profitTransferDetails
	this.TotalNum = totalNum
	this.PageSize = pageSize
	return &this
}

// NewInlineResponse20092DataWithDefaults instantiates a new InlineResponse20092Data object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20092DataWithDefaults() *InlineResponse20092Data {
	this := InlineResponse20092Data{}
	return &this
}

// GetProfitTransferDetails returns the ProfitTransferDetails field value
func (o *InlineResponse20092Data) GetProfitTransferDetails() []InlineResponse20092DataProfitTransferDetails {
	if o == nil {
		var ret []InlineResponse20092DataProfitTransferDetails
		return ret
	}

	return o.ProfitTransferDetails
}

// GetProfitTransferDetailsOk returns a tuple with the ProfitTransferDetails field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20092Data) GetProfitTransferDetailsOk() (*[]InlineResponse20092DataProfitTransferDetails, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ProfitTransferDetails, true
}

// SetProfitTransferDetails sets field value
func (o *InlineResponse20092Data) SetProfitTransferDetails(v []InlineResponse20092DataProfitTransferDetails) {
	o.ProfitTransferDetails = v
}

// GetTotalNum returns the TotalNum field value
func (o *InlineResponse20092Data) GetTotalNum() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalNum
}

// GetTotalNumOk returns a tuple with the TotalNum field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20092Data) GetTotalNumOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TotalNum, true
}

// SetTotalNum sets field value
func (o *InlineResponse20092Data) SetTotalNum(v int64) {
	o.TotalNum = v
}

// GetPageSize returns the PageSize field value
func (o *InlineResponse20092Data) GetPageSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20092Data) GetPageSizeOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PageSize, true
}

// SetPageSize sets field value
func (o *InlineResponse20092Data) SetPageSize(v int64) {
	o.PageSize = v
}

func (o InlineResponse20092Data) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["profitTransferDetails"] = o.ProfitTransferDetails
	}
	if true {
		toSerialize["totalNum"] = o.TotalNum
	}
	if true {
		toSerialize["pageSize"] = o.PageSize
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20092Data struct {
	value *InlineResponse20092Data
	isSet bool
}

func (v NullableInlineResponse20092Data) Get() *InlineResponse20092Data {
	return v.value
}

func (v *NullableInlineResponse20092Data) Set(val *InlineResponse20092Data) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20092Data) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20092Data) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20092Data(val *InlineResponse20092Data) *NullableInlineResponse20092Data {
	return &NullableInlineResponse20092Data{value: val, isSet: true}
}

func (v NullableInlineResponse20092Data) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20092Data) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


